### ISSUE TITLE
OSError: [Errno 13] Permission denied: 'indexes'

### ISSUE THREAD

**Issue by nledez** [cozy/cozy-debian#11]
```
[E 150723 15:59:52 web:1856] 500 POST /index/ (127.0.0.1) 73.18ms
[E 150723 16:01:53 web:1433] Uncaught exception POST /index/ (127.0.0.1)
    HTTPRequest(protocol='http', host='localhost:9102', method='POST', uri='/index/', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Content-Length': '402', 'Host': 'localhost:9102', 'Content-Type': 'application/json', 'Connection': 'keep-alive', 'Accept': 'application/json', 'User-Agent': 'request-json/1.0'})
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 1346, in _when_complete
        callback()
      File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 1367, in _execute_method
        self._when_complete(method(*self.path_args, **self.path_kwargs),
      File "/usr/lib/python2.7/dist-packages/cozyindexer/handlers/indexer.py", line 57, in post
        indexer.index_doc(docType, doc, fields, fieldsType)
      File "/usr/lib/python2.7/dist-packages/cozyindexer/lib/indexer.py", line 161, in index_doc
        indexSchema = IndexSchema()
      File "/usr/lib/python2.7/dist-packages/cozyindexer/lib/indexer.py", line 64, in __init__
        os.mkdir("indexes")
    OSError: [Errno 13] Permission denied: 'indexes'
```

**Comment by nledez** [comment]
Fixed in fd0d982d9a690b9fa2d951994788a04c92cfdc86
