### ISSUE TITLE
Install fails (proxy)

### ISSUE THREAD

**Issue by viki53** [cozy/cozy-debian#16]
I finally moved to Debian 8 (even though I still have some issues with Apache), so I decided to try again installing Cozy

And I got this:

```
Creating UNIX users...
Generating CouchDB tokens...
Configuring Cozy Indexer...
Configuring Cozy Controller...
Installing Cozy Platform apps...
info - Install started for home...
info - home was successfully installed.
info - Install started for proxy...
error - An error occured:
error - Install failed for proxy.
[Error: proxy CANT START]
dpkg: erreur de traitement du paquet cozy (--configure) :
 le sous-processus script post-installation installé a retourné une erreur de sortie d'état 1
Des erreurs ont été rencontrées pendant l'exécution :
 cozy
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Any idea what went wrong this time?

Also, I already have an Apache server and I saw you're using nginx: won't this create any conflict at some level?

---

EDIT: I tried again this morning after purging (`apt-get purge cozy`), same result…

**Comment by frankrousseau** [comment]
@Kloadut Can you answer to this issue?

**Comment by frankrousseau** [comment]
I don't have any idea, the proxy should install easily. How much RAM does your server have?

**Comment by viki53** [comment]
RAM is 4 GB

Here's what the Kimsufi admin tells me:

> **Motherboard**
> Intel Corporation DN2800MT
> **CPU**
> Intel(R) Atom(TM) CPU N2800 @ 1.86GHz
> _Number :_ 4
> _Cache :_ 512 KB
> _Speed :_ 1862 MHz
> **RAM**
> 2 x 2048 MB
> **Discs**
> 1 x 2000GB SATA
> **Version Real Time Monitoring**
> 0.9.4-3
> **Kernel Version**
> Debian 8.1 3.10.23-xxxx-std-ipv6-64

**Comment by clochix** [comment]
Hi @viki53,
We just published a new documentation page with some advice on [how to diagnose problems](http://cozy.io/en/host/diagnose.html) on your server. Could you run the diagnosis script mentioned at the bottom and give us the result ? Thanks !

**Comment by viki53** [comment]
Here's the output (except the first line that identifies my server):

``` shell
===== lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 8.1 (jessie)
Release:    7
Codename:   jessie
===== uname -a
Linux hostname 3.10.23-xxxx-std-ipv6-64 #1 SMP Tue Mar 18 14:48:24 CET 2014 x86_64 GNU/Linux
===== nodejs path
/usr/bin/node
/usr/bin/nodejs
===== node & nodejs version
v0.12.7
v0.12.7
===== pip list
You are using pip version 6.0.8, however version 7.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
cffi (0.8.6)
chardet (2.3.0)
colorama (0.3.2)
cozy-indexer (1.0.6)
cryptography (0.6.1)
ecdsa (0.13)
Fabric (1.10.1)
fabtools (0.19.0)
html5lib (0.999)
meld3 (1.0.0)
MySQL-python (1.2.3)
ndg-httpsclient (0.3.2)
paramiko (1.15.2)
pip (6.0.8)
ply (3.4)
pyasn1 (0.1.7)
pycparser (2.10)
pycrypto (2.6.1)
pycurl (7.19.5)
pyinotify (0.9.4)
pyOpenSSL (0.14)
python-apt (0.9.3.11)
python-dateutil (2.2)
requests (2.4.3)
setuptools (5.5.1)
six (1.8.0)
supervisor (3.0)
tornado (3.2.2)
urllib3 (1.9.1)
virtualenv (1.11.6)
wheel (0.24.0)
Whoosh (2.5.7)
===== npm -g ls -depth 0
/usr/lib
├── coffee-script@1.9.3
├── couchdb@0.3.8
├── cozy-controller@2.0.31
├── cozy-monitor@1.2.28
└── npm@2.11.3

===== supervisorctl status
cozy-controller                  RUNNING    pid 7395, uptime 14:34:46
cozy-indexer                     RUNNING    pid 7394, uptime 14:34:46
===== /etc/supervisor/conf.d/cozy-*.conf
=== /etc/supervisor/conf.d/cozy-controller.conf
[program:cozy-controller]
autorestart=true
autostart=true
command=cozy-controller
environment=NODE_ENV=production
redirect_stderr=true
user=root
priority=11
=== /etc/supervisor/conf.d/cozy-indexer.conf
[program:cozy-indexer]
autorestart=true
command=cozy-indexer
directory=/var/lib/cozy-indexer
redirect_stderr=true
user=cozy
priority=9
===== systemctl status couchdb.service
/bin/systemctl
● couchdb.service - Couchdb service
   Loaded: loaded (/lib/systemd/system/couchdb.service; enabled)
   Active: active (running) since dim. 2015-08-16 19:40:21 CEST; 1 day 3h ago
 Main PID: 6413 (beam.smp)
   CGroup: /system.slice/couchdb.service
           ├─6413 /usr/lib/erlang/erts-6.2/bin/beam.smp -Bd -K true -A 4 -- -root /usr/lib/erlang -progname erl -- -home /var/lib/couchdb -- -noshell -noinput -os_mon start_memsup false start_cpu_sup false disk_space_check_interval 1 disk_almost_full_threshold 1 -sasl errlog_type error -couch_ini /etc/couchdb/default.ini /etc/couchdb/local.ini -s couch
           └─6444 sh -s disksup

août 16 19:42:07 hostname couchdb[6413]: [info] [<0.246.0>] 127.0.0.1 - - GET / 200
août 17 08:52:58 hostname couchdb[6413]: [error] [<0.14897.1>] Could not open file /var/lib/couchdb/cozy.couch: no such file or directory
août 17 08:52:58 hostname couchdb[6413]: [info] [<0.110.0>] 127.0.0.1 - - GET /cozy/_design/cozyinstance/_view/all 404
août 17 08:54:05 hostname couchdb[6413]: [info] [<0.14896.1>] 127.0.0.1 - - GET / 200
août 17 08:54:05 hostname couchdb[6413]: [info] [<0.111.0>] 127.0.0.1 - - GET / 200
août 17 08:54:42 hostname couchdb[6413]: [info] [<0.109.0>] 127.0.0.1 - - DELETE /cozy 404
août 17 08:54:42 hostname couchdb[6413]: [info] [<0.248.0>] 127.0.0.1 - - DELETE /_config/admins/ieghuSh7 200
août 17 08:56:26 hostname couchdb[6413]: [info] [<0.14968.1>] 127.0.0.1 - - GET / 200
août 17 08:56:26 hostname couchdb[6413]: [info] [<0.14969.1>] 127.0.0.1 - - PUT /_config/admins/yai3Ochu 200
août 17 08:56:36 hostname couchdb[6413]: [info] [<0.15115.1>] 127.0.0.1 - - GET / 200
===== couchdb database directory
/var/lib/couchdb
===== couchdb database list
total 16
-rw-r--r-- 1 couchdb couchdb 4194 août  16 19:40 _replicator.couch
-rw-r--r-- 1 couchdb couchdb 4194 août  16 19:40 _users.couch
===== curl 127.0.0.1:5984/cozy
{"error":"not_found","reason":"no_db_file"}
===== ls -l /etc/cozy
total 12
-rw-r--r-- 1 root             root 134 août  17 08:56 controller.json
-rw-r----- 1 cozy-data-system root  18 août  17 08:56 couchdb.login
-rw------- 1 root             root  32 août  17 08:56 stack.token
===== find /usr/local/cozy*
find: AVERTISSEMENT : vous avez spécifié l'option -maxdepth après un argument qui n'est pas une option -type mais les options sont positionnelles (-maxdepth affecte les tests spécifiés avant aussi bien qu'après). SVP spécifiez des options avant les autres arguments. 

141289    4 drwxr-sr-x   3 root     staff        4096 août 17 08:56 /usr/local/cozy
141290    4 drwxrwxrwx   3 root     staff        4096 août 17 08:56 /usr/local/cozy/apps
141292    4 drwxr-xr-x   8 cozy-data-system cozy-data-system     4096 août 17 08:56 /usr/local/cozy/apps/data-system
===== All logs
=== /var/log/supervisor/cozy-controller-stdout---supervisor-8T7WSN.log
info - data-system:git clone
info - data-system:npm install
info - npm:install:success
info - data-system:start application
info - data-system:restart
info - data-system:restart
info - data-system:restart
info - data-system:restart
error - Callback on Exit
error - Error: data-system CANT START
Sending error to client :
Error: data-system CANT START
    at onExit (/usr/lib/node_modules/cozy-controller/build/server/lib/spawner.js:119:25)
    at listener (/usr/lib/node_modules/cozy-controller/node_modules/forever-monitor/node_modules/broadway/node_modules/eventemitter2/lib/eventemitter2.js:251:10)
    at EventEmitter.emit (/usr/lib/node_modules/cozy-controller/node_modules/forever-monitor/node_modules/broadway/node_modules/eventemitter2/lib/eventemitter2.js:339:22)
    at letChildDie (/usr/lib/node_modules/cozy-controller/node_modules/forever-monitor/lib/forever-monitor/monitor.js:172:12)
    at ChildProcess.<anonymous> (/usr/lib/node_modules/cozy-controller/node_modules/forever-monitor/lib/forever-monitor/monitor.js:186:7)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
[Mon, 17 Aug 2015 06:57:19 GMT] - POST /drones/data-system/start - 400 - 39252.386 ms -  941
=== /var/log/supervisor/cozy-indexer-stdout---supervisor-0i4xA7.log
[I 150817 08:56:35 server:25] Cozy Data Indexer started on port 9102.
[I 150817 08:56:38 web:1856] 200 GET / (127.0.0.1) 1.83ms
=== /usr/local/var/log/cozy/data-system.log-backup
    at /usr/lib/node_modules/cozy-controller/node_modules/cozy-controller-carapace/bin/carapace:50:11
    at EventEmitter.carapace.use (/usr/lib/node_modules/cozy-controller/node_modules/cozy-controller-carapace/lib/carapace.js:103:5)
    at configure (/usr/lib/node_modules/cozy-controller/node_modules/cozy-controller-carapace/bin/carapace:45:12)
    at Object.<anonymous> (/usr/lib/node_modules/cozy-controller/node_modules/cozy-controller-carapace/bin/carapace:84:5)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
/usr/lib/node_modules/cozy-controller/node_modules/cozy-controller-carapace/lib/plugins/net.js:31
    throw new Error('No appropiate net override for node version ' + version);
          ^
Error: No appropiate net override for node version v0.12.7
    at EventEmitter.carapace.net (/usr/lib/node_modules/cozy-controller/node_modules/cozy-controller-carapace/lib/plugins/net.js:31:11)
    at /usr/lib/node_modules/cozy-controller/node_modules/cozy-controller-carapace/bin/carapace:58:23
    at iterate (/usr/lib/node_modules/cozy-controller/node_modules/cozy-controller-carapace/node_modules/async/lib/async.js:108:13)
    at Object.async.forEachSeries (/usr/lib/node_modules/cozy-controller/node_modules/cozy-controller-carapace/node_modules/async/lib/async.js:124:9)
    at /usr/lib/node_modules/cozy-controller/node_modules/cozy-controller-carapace/bin/carapace:50:11
    at EventEmitter.carapace.use (/usr/lib/node_modules/cozy-controller/node_modules/cozy-controller-carapace/lib/carapace.js:103:5)
    at configure (/usr/lib/node_modules/cozy-controller/node_modules/cozy-controller-carapace/bin/carapace:45:12)
    at Object.<anonymous> (/usr/lib/node_modules/cozy-controller/node_modules/cozy-controller-carapace/bin/carapace:84:5)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

**Comment by clochix** [comment]
Hi @viki53,
What version on Node are you using ? Cozy only works with 0.10.x for now, and it seems you're using 0.12.7 Could you check ?

**Comment by viki53** [comment]
Yes, I have the latest version installed. Is that really a problem to have a newer version?

**Comment by clochix** [comment]
Unfortunately yes, as new versions of Node are not backward compatibles, some API have changed and we now Cozy doesn't work with Node 0.12. If you don't have any other application depending on version 0.12, you should install latest 0.10 package. Otherwise, there are some solutions allowing to use different versions of Node in parallel.

**Comment by clochix** [comment]
Hello @viki53, any news ? Did you manage to switch to Node 0.10 and install Cozy ?

**Comment by viki53** [comment]
Sorry, I haven't had time yet to test my projects to check if they work with Node 0.10 (but I doubt it, as most dependencies are pretty recent).

Any idea when Cozy will be compatible with newer versions of Node.js?

**Comment by clochix** [comment]
We are working on it, but it's not one of our top priorities, so we have no ETA for now.

Maybe could you try to use some Node version manager, like [nvm](https://github.com/creationix/nvm) or [ndenv](https://github.com/riywo/ndenv).

**Comment by viki53** [comment]
Hi,

Any news about this?

I tried installing nvm to use Node 0.10.40 but didn't get much luck when trying to install Cozy again.

**Comment by clochix** [comment]
Hi @viki53,
We are still working on supporting Node 0.12. I haven't fully tested all the applications now, but the next versions, awaited in a few days, should mostly work with Node 0.12. Stay tuned !

**Comment by viki53** [comment]
Great!

What about Node 4.2? Have you tested it too?

I'm pretty impatient to test Cozy if I can replace ownCloud with its slow and buggy behavior…

**Comment by frankrousseau** [comment]
Yes, we want to move to Node 4.2. It's the first version labelized as a Long Term Support version.

**Comment by clochix** [comment]
Not yet, but it's definitively on our roadmap, as this version is a LTS.

**Comment by viki53** [comment]
Awesome!

Any idea when the next version will be released on Debian repos?

Also, I can't seem to find a timeline of the versions or a changelog. Am I missing something?

**Comment by nicofrand** [comment]
For the changelog, I agree that might be a little difficult to find but here it is: https://cozy.io/en/hack/releases/

**Comment by viki53** [comment]
Thanks!

**Comment by fairyfeller** [comment]
I have exactly same problem - clean VDS with Debian 8.2 and Nginx + PHP-FPM

```
root@digihost:/# sudo npm install cozy-controller -g
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.10.29","npm":"1.4.21"})
/usr/local/bin/cozy-controller -> /usr/local/lib/node_modules/cozy-controller/bin/cozy-controller
cozy-controller@2.0.38 /usr/local/lib/node_modules/cozy-controller
├── rimraf@2.2.8
├── printit@0.1.6
├── mozilla-version-comparator@1.0.2
├── async@0.9.0
├── mkdirp@0.5.0 (minimist@0.0.8)
├── request-json-light@0.5.22 (mime@1.3.4, form-data@1.0.0-rc3)
├── cozy-controller-carapace@0.8.0 (eventemitter2@0.4.14, semver@1.0.14, async@0.1.22, optimist@0.3.7)
├── tar@0.1.17 (inherits@1.0.2, block-stream@0.0.8, fstream@0.1.31)
├── americano@0.3.10 (errorhandler@1.0.1, commander@2.2.0, printit@0.1.3, morgan@1.1.1, method-override@2.0.0, body-parser@1.3.0, express@4.4.0)
├── request@2.53.0 (caseless@0.9.0, aws-sign2@0.5.0, forever-agent@0.5.2, form-data@0.2.0, stringstream@0.0.5, oauth-sign@0.6.0, tunnel-agent@0.4.2, isstream@0.1.2, json-stringify-safe@5.0.1, node-uuid@1.4.7, qs@2.3.3, combined-stream@0.0.7, mime-types@2.0.14, tough-cookie@2.2.1, http-signature@0.10.1, bl@0.9.4, hawk@2.3.1)
├── forever-monitor@1.3.0 (watch@0.5.1, pkginfo@0.3.1, minimatch@0.2.14, utile@0.1.7, ps-tree@0.0.3, broadway@0.2.10)
├── americano-cozy@0.2.8 (printit@0.1.3, jugglingdb@0.2.14, jugglingdb-cozy-adapter@0.4.12)
├── npm@1.4.28
└── latest@0.2.0 (npm@2.14.15)
```

**Comment by fairyfeller** [comment]
Also i tried to update Node to 0.12.0 and to 0.10.40, but still has no luck :(
Any chance on solving this ? 

```
root@digihost:~# sudo npm install cozy-controller -g
npm WARN engine npm@1.4.28: wanted: {"node":">=0.8","npm":"1"} (current: {"node":"0.12.0","npm":"2.5.1"})
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.12.0","npm":"2.5.1"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.12.0","npm":"2.5.1"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.12.0","npm":"2.5.1"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.12.0","npm":"2.5.1"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.12.0","npm":"2.5.1"})
/usr/local/bin/cozy-controller -> /usr/local/lib/node_modules/cozy-controller/bin/cozy-controller
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/readdir-scoped-modules requires graceful-fs@'^4.1.2' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/graceful-fs,
npm WARN unmet dependency which is version 3.0.5
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/read-cmd-shim requires graceful-fs@'^4.1.2' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/graceful-fs,
npm WARN unmet dependency which is version 3.0.5
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/read-package-tree requires read-package-json@'^2.0.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/read-package-json,
npm WARN unmet dependency which is version 1.2.7
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npmconf requires semver@'2' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/semver,
npm WARN unmet dependency which is version 4.2.0
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npmconf requires uid-number@'0.0.5' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/uid-number,
npm WARN unmet dependency which is version 0.0.6
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data requires semver@'2 || 3' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/semver,
npm WARN unmet dependency which is version 4.2.0
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npm-registry-client/node_modules/couch-login requires request@'~2.9.202' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/request,
npm WARN unmet dependency which is version 2.53.0
cozy-controller@2.0.38 /usr/local/lib/node_modules/cozy-controller
├── rimraf@2.2.8
├── printit@0.1.6
├── mozilla-version-comparator@1.0.2
├── async@0.9.0
├── mkdirp@0.5.0 (minimist@0.0.8)
├── request-json-light@0.5.22 (mime@1.3.4, form-data@1.0.0-rc3)
├── cozy-controller-carapace@0.8.0 (eventemitter2@0.4.14, semver@1.0.14, async@0.1.22, optimist@0.3.7)
├── tar@0.1.17 (inherits@1.0.2, block-stream@0.0.8, fstream@0.1.31)
├── americano@0.3.10 (errorhandler@1.0.1, commander@2.2.0, printit@0.1.3, morgan@1.1.1, method-override@2.0.0, body-parser@1.3.0, express@4.4.0)
├── request@2.53.0 (caseless@0.9.0, aws-sign2@0.5.0, forever-agent@0.5.2, form-data@0.2.0, stringstream@0.0.5, oauth-sign@0.6.0, tunnel-agent@0.4.2, isstream@0.1.2, json-stringify-safe@5.0.1, node-uuid@1.4.7, qs@2.3.3, combined-stream@0.0.7, mime-types@2.0.14, tough-cookie@2.2.1, http-signature@0.10.1, bl@0.9.4, hawk@2.3.1)
├── americano-cozy@0.2.8 (printit@0.1.3, jugglingdb@0.2.14, jugglingdb-cozy-adapter@0.4.12)
├── forever-monitor@1.3.0 (watch@0.5.1, pkginfo@0.3.1, minimatch@0.2.14, utile@0.1.7, ps-tree@0.0.3, broadway@0.2.10)
├── npm@1.4.28
└── latest@0.2.0 (npm@2.14.15)
```

**Comment by jsilvestre** [comment]
It's been fixed for a while now!
